#!/usr/bin/env python3
"""Build every generated Claudovsky file from its canonical sources.

Canonical, hand-edited sources (all under src/):
  - src/dictionary.md          the word list (Word | Meaning | Use in place of | Short gloss)
  - src/rules.md               the behavioral rules, as PROSE/SKILL renderings per section
  - src/install-steps/*.md     hand-written "go here, click that" steps per platform+mode,
                                each with a {{INSTRUCTIONS_BLOCK}} placeholder where the
                                generated paste-block goes (claude-per-session.md has none —
                                it points at the .skill file instead, so it's copied
                                through with just an auto-generated header)

Run from anywhere after editing any of the above, before committing:

    python3 src/build.py

Generated (never hand-edit these — edit the sources above instead):
  - claude/always-on.md, claude/per-session.md
  - chatgpt/always-on.md, chatgpt/per-session.md
  - gemini/always-on.md, gemini/per-session.md
  - claude/claudovsky.skill — built entirely in memory, never unpacked to disk.
    Its two entries (SKILL.md, reference/dictionary.md) are rendered as strings
    from the same sources as everything else and written straight into the zip.

NOT touched by this script (prose/overview pages, hand-maintained):
  README.md, claude/README.md, chatgpt/README.md, gemini/README.md
"""
import io
import pathlib
import re
import sys
import textwrap
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
DICTIONARY = ROOT / "src" / "dictionary.md"
RULES = ROOT / "src" / "rules.md"
INSTALL_STEPS = ROOT / "src" / "install-steps"
SKILL_ZIP = ROOT / "claude" / "claudovsky.skill"

AUTO_HEADER = (
    "<!-- AUTO-GENERATED by src/build.py from src/dictionary.md, "
    "src/rules.md, and src/install-steps/{source} — do not hand-edit this file, "
    "change the sources and re-run the script. -->\n\n"
)

TABLE_ROW_RE = re.compile(
    r"^\|\s*(?P<word>[^|]+?)\s*\|\s*(?P<meaning>[^|]+?)\s*\|"
    r"\s*(?P<usein>[^|]+?)\s*\|\s*(?P<gloss>[^|]+?)\s*\|\s*$"
)

SKILL_RULE_IDS = [
    "substitute_dont_append",
    "intensity_levels",
    "word_list_only",
    "no_invented_phrases",
    "somber_exception",
    "hard_rule_death",
    "dont_overexplain",
    "toggle",
    "combining_words",
]

TARGETS = [
    dict(
        name="claude-always-on", platform="Claude",
        install_steps="claude-always-on.md", output="claude/always-on.md",
        sections=["opening_frame", "somber_exception", "hard_rule_death", "intensity_levels",
                  "word_list_only", "no_invented_phrases", "combining_words", "toggle", "freshness_fetch"],
        embed_wordlist=True, wordlist_prefix="Word list:\n",
    ),
    dict(
        name="chatgpt-always-on", platform="ChatGPT",
        install_steps="chatgpt-always-on.md", output="chatgpt/always-on.md",
        sections=["opening_frame", "somber_exception", "hard_rule_death", "intensity_levels",
                  "word_list_only", "no_invented_phrases", "combining_words", "toggle", "freshness_fetch"],
        embed_wordlist=True, wordlist_prefix="Word list (substitute for the plain English word):\n",
    ),
    dict(
        name="gemini-always-on", platform="Gemini",
        install_steps="gemini-always-on.md", output="gemini/always-on.md",
        sections=["opening_frame", "somber_exception", "hard_rule_death", "intensity_levels",
                  "word_list_only", "no_invented_phrases", "combining_words", "toggle", "freshness_fetch"],
        embed_wordlist=True, wordlist_prefix="Word list:\n",
    ),
    dict(
        name="chatgpt-per-session", platform="ChatGPT", container="GPT",
        install_steps="chatgpt-per-session.md", output="chatgpt/per-session.md",
        sections=["opening_frame_session", "somber_exception", "hard_rule_death", "intensity_levels",
                  "word_list_only_session", "no_invented_phrases", "combining_words", "toggle_session",
                  "freshness_fetch"],
        embed_wordlist=True, wordlist_prefix="Word list:\n",
    ),
    dict(
        name="gemini-per-session", platform="Gemini", container="Gem",
        install_steps="gemini-per-session.md", output="gemini/per-session.md",
        sections=["opening_frame_session", "somber_exception", "hard_rule_death", "intensity_levels",
                  "word_list_only_session", "no_invented_phrases", "combining_words", "toggle_session",
                  "freshness_fetch"],
        embed_wordlist=True, wordlist_prefix="Word list:\n",
    ),
    dict(
        name="claude-per-session", platform="Claude",
        install_steps="claude-per-session.md", output="claude/per-session.md",
        sections=[], embed_wordlist=False,
    ),
]


def parse_dictionary_rows(master_content: str):
    rows = []
    in_table = False
    for line in master_content.splitlines():
        if line.startswith("| Word |"):
            in_table = True
            continue
        if not in_table:
            continue
        if line.startswith("|---"):
            continue
        if not line.startswith("|"):
            break
        match = TABLE_ROW_RE.match(line)
        if not match:
            raise ValueError(f"Could not parse dictionary table row: {line!r}")
        primary = re.split(r"\s*[(/]", match.group("word"), maxsplit=1)[0].strip()
        rows.append((primary, match.group("gloss")))
    if not rows:
        raise ValueError("No dictionary rows found — table format may have changed.")
    return rows


def build_wordlist_text(rows) -> str:
    joined = "; ".join(f"{word}={gloss}" for word, gloss in rows) + "."
    return textwrap.fill(joined, width=72, break_long_words=False, break_on_hyphens=False)


def parse_rules(rules_content: str):
    if rules_content.startswith("---"):
        rules_content = rules_content[rules_content.index("---", 3) + 3:]
    sections = {}
    current_id = None
    current_field = None
    buffer = []

    def flush():
        if current_id and current_field:
            content = "\n".join(buffer).strip("\n")
            sections.setdefault(current_id, {})[current_field] = content

    for line in rules_content.split("\n"):
        if line.startswith("## "):
            flush()
            current_id = line[3:].strip()
            current_field = None
            buffer = []
            continue
        if line.strip() == "PROSE:":
            flush()
            current_field = "PROSE"
            buffer = []
            continue
        if line.strip() == "SKILL:":
            flush()
            current_field = "SKILL"
            buffer = []
            continue
        if current_id is not None and current_field is not None:
            buffer.append(line)
    flush()
    return sections


def render_block(target, rules, wordlist_text) -> str:
    parts = ["---- Claudovsky ----"]
    for section_id in target["sections"]:
        entry = rules.get(section_id)
        if not entry or "PROSE" not in entry:
            raise ValueError(f"Missing PROSE for section {section_id!r} (target {target['name']})")
        rendered = entry["PROSE"]
        rendered = rendered.replace("{PLATFORM}", target["platform"])
        rendered = rendered.replace("{CONTAINER}", target.get("container", ""))
        parts.append(rendered)
    if target.get("embed_wordlist"):
        parts.append(target.get("wordlist_prefix", "Word list:\n") + wordlist_text)
    parts.append("---- end Claudovsky ----")
    return "\n\n".join(parts)


def render_skill_rules(rules) -> str:
    parts = []
    for rid in SKILL_RULE_IDS:
        entry = rules.get(rid, {})
        skill_text = entry.get("SKILL")
        if skill_text is None:
            raise ValueError(f"Missing SKILL text for {rid!r}")
        parts.append(skill_text)
    return "\n".join(parts)


def write_if_changed(path: pathlib.Path, content: str, changed: list) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text() != content:
        path.write_text(content)
        changed.append(path)


def main() -> int:
    if not DICTIONARY.exists():
        sys.exit(f"Master dictionary not found: {DICTIONARY}")
    if not RULES.exists():
        sys.exit(f"Rules file not found: {RULES}")

    dict_content = DICTIONARY.read_text()
    rules_content = RULES.read_text()
    rows = parse_dictionary_rows(dict_content)
    wordlist_text = build_wordlist_text(rows)
    rules = parse_rules(rules_content)

    changed = []

    # 1-3: per-platform always-on / per-session / snippet files, from install-steps + rules.
    for target in TARGETS:
        install_path = INSTALL_STEPS / target["install_steps"]
        if not install_path.exists():
            raise ValueError(f"Missing install-steps file: {install_path}")
        install_text = install_path.read_text()
        if target["sections"]:
            block = render_block(target, rules, wordlist_text)
            fenced = "```\n" + block + "\n```"
            if "{{INSTRUCTIONS_BLOCK}}" not in install_text:
                raise ValueError(f"{install_path} has no {{{{INSTRUCTIONS_BLOCK}}}} placeholder")
            body = install_text.replace("{{INSTRUCTIONS_BLOCK}}", fenced)
        else:
            body = install_text
        header = AUTO_HEADER.format(source=target["install_steps"])
        write_if_changed(ROOT / target["output"], header + body, changed)

    # 4: bundled skill dictionary — exact copy of the master, with its own auto header.
    if dict_content.startswith("---"):
        end = dict_content.index("---", 3) + 3
        dict_header_note = (
            "<!-- AUTO-GENERATED by src/build.py from src/dictionary.md — "
            "do not hand-edit this file, edit the master and re-run the script. -->\n"
        )
        skill_dict_content = dict_content[:end] + "\n" + dict_header_note + dict_content[end:]
    else:
        skill_dict_content = dict_content

    # 5: SKILL.md — wrapper (install-steps/claude-skill-wrapper.md) + generated Rules list.
    wrapper_path = INSTALL_STEPS / "claude-skill-wrapper.md"
    if not wrapper_path.exists():
        raise ValueError(f"Missing skill wrapper: {wrapper_path}")
    wrapper_text = wrapper_path.read_text()
    if "{{RULES_LIST}}" not in wrapper_text:
        raise ValueError(f"{wrapper_path} has no {{{{RULES_LIST}}}} placeholder")
    skill_md_content = wrapper_text.replace("{{RULES_LIST}}", render_skill_rules(rules))

    # 6: repack claude/claudovsky.skill fresh, entirely in memory. No unpacked
    # folder is ever written to disk — the two entries above are rendered as
    # strings and written straight into the archive. A fixed date_time keeps
    # the zip byte-for-byte reproducible when content hasn't changed (writestr
    # defaults to the current wall-clock time, which would make every run
    # look "changed" even with identical content).
    SKILL_ZIP.parent.mkdir(parents=True, exist_ok=True)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for arcname, content in (
            ("claudovsky/SKILL.md", skill_md_content),
            ("claudovsky/reference/dictionary.md", skill_dict_content),
        ):
            zi = zipfile.ZipInfo(arcname, date_time=(1980, 1, 1, 0, 0, 0))
            zi.compress_type = zipfile.ZIP_DEFLATED
            zi.external_attr = 0o644 << 16
            zf.writestr(zi, content)
    new_bytes = buf.getvalue()
    old_bytes = SKILL_ZIP.read_bytes() if SKILL_ZIP.exists() else None
    if old_bytes != new_bytes:
        SKILL_ZIP.write_bytes(new_bytes)
        changed.append(SKILL_ZIP)

    if changed:
        print("Regenerated:")
        for path in changed:
            print(f"  - {path.relative_to(ROOT)}")
    else:
        print("Already in sync — nothing to do.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
